TESTS WITH ERRORS 
test03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 73, in test03
    self.compare(self.KB.kb_explain(fact4), answer1)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 199, in kb_explain
    string = "fact: (" + fact.statement.predicate + " " + str(fact.statement.terms[0]) + " " + str(fact.statement.terms[1]) + ")"
IndexError: list index out of range

-------------------------------
TESTS FAILED  
-------------------------------
TESTS SKIPPED 
-------------------------------
